apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: back=angelaranda04/quarkus-prueba:~2.1.x
    argocd-image-updater.argoproj.io/back.update-strategy: semver
    argocd-image-updater.argoproj.io/back.platforms: linux/amd64
    # argocd-image-updater.argoproj.io/back.allow-tags: regexp:^[0-9]{2})([0-9]{2})([0-9]{4})([0-9]{2})([0-9]{2})-([0-9a-z]{5}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master:image-updater-{{.NewTag}}
    argocd-image-updater.argoproj.io/back.force-update: "true"
    argocd-image-updater.argoproj.io/back.ignore-tags: latest
  name: ats
  namespace: argocd
spec:
  project: argocd-demo
  source:
    repoURL: https://github.com/angelaranda200/argocd-prueba.git
    targetRevision: HEAD
    path: deploy-prueba/overlays/bronze
  destination:
    server: https://kubernetes.default.svc
    namespace: ats-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    automated:
      selfHeal: true
      prune: true